apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  labels:
    app: postgres
data:
  POSTGRES_DB: app-db
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256